export const ALERT_AUDIO_PLACEHOLDER = '#'

const alertAudioModules = import.meta.glob('../audios/*', {
  eager: true,
  import: 'default',
  query: '?url',
})

const getAlertAudio = (...fileNames) => {
  for (const fileName of fileNames) {
    const audio = alertAudioModules[`../audios/${fileName}`]

    if (audio) {
      return audio
    }
  }

  return ALERT_AUDIO_PLACEHOLDER
}

export const ALERT_AUDIO = {
  aiGuideClick: getAlertAudio('AI Guide click.wav'),
  allConnectionsCompleted: getAlertAudio('Guide all complete conn.wav'),
  autoConnect: getAlertAudio('Autoconnect.wav'),
  connect1To9: getAlertAudio('Connect terminal 1 to terminal 9.wav', 'Correct Connections.wav'),
  connect2To10: getAlertAudio('Connect terminal 2 to terminal 10.wav', "Let's move on to the next connection.wav"),
  connect3To11: getAlertAudio('Now, connect terminal 3 of the voltmeter to terminal 11.wav'),
  connect4To12: getAlertAudio('Connect terminal 4 to terminal 12.wav'),
  connect5To13: getAlertAudio('Connect terminal 5 to terminal 13.wav'),
  connect6To14: getAlertAudio('Connect terminal 6 to terminal 14..wav'),
  connect7To15: getAlertAudio('Connect terminal 7 to terminal 15.wav'),
  connect8To16: getAlertAudio('Connect terminal 8 to terminal 16.wav'),
  connectionsVerified: getAlertAudio('For correct connections, check click.wav'),
  correctCalculations: getAlertAudio('Verify button click, Correct calculations.wav'),
  calculateButtonClick: getAlertAudio('After clicking the Calculate button.wav'),
  duplicateReading: getAlertAudio('For Duplicate Readings, Add click.wav'),
  fifthReadingAdded: getAlertAudio('5th reading added.wav'),
  firstCheckClick: getAlertAudio('1st time check button click.wav'),
  firstPowerSupplyClick: getAlertAudio('1st time Power Supply click.wav'),
  firstReadingAdded: getAlertAudio('1st readings added.wav'),
  graph: getAlertAudio('Graph 2.wav'),
  insufficientReadings: getAlertAudio('InsufficientReadings.wav'),
  incorrectCalculations: getAlertAudio('Verify button click, Incorrect calculations.wav'),
  maxReadings: getAlertAudio('For max. readings, add button click.wav'),
  multipleWrongConnections: getAlertAudio('Multiple wrong connections.wav'),
  powerSupplyTurnOn: getAlertAudio('powerSupplyTurnOn.wav'),
  print: getAlertAudio('Print.wav'),
  reportGenerated: getAlertAudio('Generate Report button click.wav'),
  reset: getAlertAudio('Reset.wav'),
  resistanceRequired: getAlertAudio('After correct connections, ps click.wav'),
  resistanceSet: getAlertAudio('After resistance is set.wav'),
  secondReadingAdded: getAlertAudio('2nd readings added.wav'),
  sixReadingsAdded: getAlertAudio('After 6 readings, Graph click.wav'),
  tenReadingsAdded: getAlertAudio('After 10 readings have been done.wav'),
  voltageSet: getAlertAudio('Voltage is set.wav'),
  verifyMultipleValuesMissing: getAlertAudio('Verify button click, more than one value is missing.wav'),
  verifyOneValueMissing: getAlertAudio('Verify button click, one value is missing.wav'),
  wrongConnection: getAlertAudio('Wrong connection.wav'),
}

export const EXPERIMENT_ALERTS = {
  connectionMode: {
    dedupeKey: 'step-1-connection-mode',
    description: 'Drag nodes from apparatus to complete the circuit connections.',
    icon: '🔌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Connection Mode Activated',
    type: 'info',
  },
  circuitConnectionsCompleted: {
    audio: ALERT_AUDIO.autoConnect,
    description: 'Now set the required resistance value by moving the resistance sliders.',
    icon: '✅',
    stepNumber: 1,
    target: '#resistance-controls',
    title: 'Autoconnect completed.',
    type: 'success',
  },
  allConnectionsCompleted: {
    audio: ALERT_AUDIO.allConnectionsCompleted,
    description: '',
    icon: '✅',
    stepNumber: 1,
    target: '#check-button',
    title: 'All connections are completed. Click on the check button to verify the connections.',
    type: 'success',
  },
  incorrectNodeConnection: {
    audio: ALERT_AUDIO.wrongConnection,
    dedupeKey: 'wrong-connection',
    description: 'Remove the wrong wire and follow the highlighted terminals.',
    icon: '❌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'This connection is wrong.',
    type: 'error',
  },
  checkingConnections: {
    description: 'The lab console is validating each wire path.',
    duration: 2200,
    icon: '🎛️',
    stepNumber: 2,
    target: '#check-button',
    title: 'Checking Circuit Connections...',
    type: 'info',
  },
  connectionsVerified: {
    audio: ALERT_AUDIO.connectionsVerified,
    description: 'Connections Verified successfully. Now set the required resistance value by moving the resistance sliders.',
    icon: '✅',
    stepNumber: 2,
    target: '#resistance-controls',
    title: 'Connections Verified',
    type: 'success',
  },
  connectionErrorFound: {
    audio: ALERT_AUDIO.multipleWrongConnections,
    icon: '⚠️',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Connection Error Found - Please Recheck Wiring',
    type: 'error',
  },
  requiredConnectionsFirst: {
    audio: ALERT_AUDIO.firstCheckClick,
    description: '',
    icon: '!',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Please make the required connections as per the given instructions.',
    type: 'warning',
  },
  missingConnections: {
    audio: ALERT_AUDIO.firstCheckClick,
    description: 'Some required connections are missing. Follow the highlighted terminals to complete the circuit.',
    icon: '!',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Please make the required connections as per the given instructions.',
    type: 'warning',
  },
  wrongConnectionsFound: {
    audio: ALERT_AUDIO.multipleWrongConnections,
    description: 'Remove the wrong wire and follow the highlighted terminals.',
    icon: '!',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Wrong Connection Found',
    type: 'error',
  },
  multipleWrongConnections: {
    audio: ALERT_AUDIO.multipleWrongConnections,
    description: '',
    icon: '!',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Some connections are wrong.',
    type: 'error',
  },
  adjustResistance: {
    audio: ALERT_AUDIO.resistanceRequired,
    dedupeKey: 'step-3-adjust-resistance',
    description: '',
    icon: '🎛️',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Please set R1, R2 and R3 by moving the resistance sliders before turning ON the power supply.',
    type: 'info',
  },
  resistanceValuesSelected: {
    audio: ALERT_AUDIO.resistanceSet,
    description: 'The resistance values for R1, R2, and R3 have been set. Click on the Power to turn ON the power supply.',
    icon: 'OK',
    stepNumber: 3,
    target: '#power-toggle-button',
    title: 'Resistance Values Selected Successfully',
    type: 'success',
  },
  resistanceLocked: {
    description: 'Resistance controls are locked while the circuit is powered.',
    icon: '✅',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Resistance Values Locked for Experiment',
    type: 'success',
  },
  powerOn: {
    audio: ALERT_AUDIO.powerSupplyTurnOn,
    description: '',
    icon: '⚡',
    stepNumber: 4,
    target: '#voltage-control',
    title: 'Power supply has been turned ON. Now, set the voltage by moving the voltage slider.',
    type: 'success',
  },
  powerOffDuringExperiment: {
    audio: ALERT_AUDIO_PLACEHOLDER,
    description: '',
    icon: '⚠️',
    stepNumber: 4,
    target: '#power-toggle-button',
    title: 'You turned off the power supply. Turn it back on to continue the simulation.',
    type: 'warning',
  },
  cannotStartPower: {
    audio: ALERT_AUDIO.firstPowerSupplyClick,
    description: '',
    icon: '⚠️',
    stepNumber: 4,
    target: '#check-button',
    title: 'Please complete or check the connections first to turn on the power supply.',
    type: 'warning',
  },
  adjustVoltage: {
    dedupeKey: 'step-5-adjust-voltage',
    description: 'Move the voltage control and watch the meter needles respond.',
    icon: '⚡',
    stepNumber: 5,
    target: '#voltage-control',
    title: 'Adjust Voltage to Observe Voltmeter Readings',
    type: 'info',
  },
  currentUpdating: {
    dedupeKey: 'step-5-current-updating',
    description: 'The voltmeter values are linked to the active supply voltage.',
    duration: 2600,
    icon: '📊',
    stepNumber: 5,
    target: '#equipment-panel',
    title: 'Current Readings Updating in Real Time',
    type: 'info',
  },
  addingReading: {
    audio: ALERT_AUDIO_PLACEHOLDER,
    description: 'The current values are being transferred to the table.',
    duration: 1800,
    icon: '📊',
    stepNumber: 6,
    target: '#observation-table-panel',
    title: 'Adding Current Readings to Observation Table',
    type: 'info',
  },
  readingAdded: {
    audio: ALERT_AUDIO.firstReadingAdded,
    description: 'To record the second reading, change the voltage and click the Add button again.',
    icon: '✅',
    stepNumber: 6,
    target: '#observation-table-panel',
    title: 'Readings added successfully.',
    type: 'success',
  },
  secondReadingAdded: {
    audio: ALERT_AUDIO.secondReadingAdded,
    description: 'Change the voltage and add the third reading. At least three readings are required.',
    icon: 'OK',
    stepNumber: 6,
    target: '#voltage-control',
    title: 'Second reading added successfully.',
    type: 'success',
  },
  readingAlreadyExists: {
    audio: ALERT_AUDIO.duplicateReading,
    description: 'This reading is already added to the table. Change the voltage value and take the next reading.',
    icon: '⚠️',
    stepNumber: 6,
    target: '#voltage-control',
    title: 'Duplicate Readings',
    type: 'warning',
  },
  continueReadings: {
    description: 'Record readings at different voltage settings before plotting.',
    icon: '📊',
    stepNumber: 7,
    target: '#add-reading-button',
    title: 'Continue Taking Readings Until Minimum 6 Entries',
    type: 'info',
  },
  minimumReadingsRequired: {
    audio: ALERT_AUDIO.insufficientReadings,
    icon: '⚠️',
    stepNumber: 7,
    target: '#observation-table-panel',
    title: 'Minimum 3 Readings Required for Verification',
    type: 'warning',
  },
  sufficientData: {
    audio: ALERT_AUDIO_PLACEHOLDER,
    description: 'Now verify KVL in the theoretical verification section, or record up to two more readings.',
    icon: '✅',
    stepNumber: 7,
    target: '#calculation-panel',
    title: 'Third reading added successfully.',
    type: 'success',
  },
  tenReadingsRecorded: {
    audio: ALERT_AUDIO_PLACEHOLDER,
    description: 'Now verify KVL in the theoretical verification section.',
    icon: 'OK',
    stepNumber: 7,
    target: '#calculation-panel',
    title: 'All five readings have been recorded.',
    type: 'success',
  },
  maxReadingsReached: {
    audio: ALERT_AUDIO.maxReadings,
    description: 'Now verify KVL in the theoretical verification section.',
    icon: '!',
    stepNumber: 7,
    target: '#calculation-panel',
    title: 'You can add up to five readings to the table.',
    type: 'warning',
  },
  lastReadingAdded: {
    audio: ALERT_AUDIO.fifthReadingAdded,
    description: '',
    icon: 'OK',
    stepNumber: 7,
    target: '#verify-button',
    title: 'Last reading added successfully. Now click the “Calculate” button to verify the KVL theoretically.',
    type: 'success',
  },
  calculationInstructions: {
    audio: ALERT_AUDIO.calculateButtonClick,
    description: '',
    icon: 'OK',
    stepNumber: 8,
    target: '#calculation-panel',
    title: 'The resistance values are prefilled in the “Resistance Values” panel under the “Theoretical Verification” section. Calculate the branch currents theoretically using the equations provided in the “Equations” button. Enter the calculated current and resistance values in the input fields, then click the “Verify” button to verify KVL.',
    type: 'info',
  },
  multipleCalculationValuesMissing: {
    audio: ALERT_AUDIO.verifyMultipleValuesMissing,
    audioSpeech: ALERT_AUDIO.verifyMultipleValuesMissing === ALERT_AUDIO_PLACEHOLDER
      ? 'Please enter all the values, then click the “Verify” button to verify KVL.'
      : '',
    description: '',
    icon: '!',
    stepNumber: 8,
    target: '#calculation-panel',
    title: 'Please enter all the values, then click the “Verify” button to verify KVL.',
    type: 'warning',
  },
  calculationValueMissing: {
    audio: ALERT_AUDIO.verifyOneValueMissing,
    description: '',
    icon: '!',
    stepNumber: 8,
    target: '#calculation-panel',
    title: 'Please enter the required value, then click the “Verify” button to verify KVL.',
    type: 'warning',
  },
  incorrectCalculations: {
    audio: ALERT_AUDIO.incorrectCalculations,
    description: '',
    icon: '!',
    stepNumber: 8,
    target: '#calculation-panel',
    title: 'Incorrect calculations. Kirchhoff’s Voltage Law (KVL) is not verified. Please review your calculations and try again.',
    type: 'error',
  },
  correctCalculations: {
    audio: ALERT_AUDIO.correctCalculations,
    description: '',
    icon: 'OK',
    stepNumber: 8,
    target: '#generate-report-button',
    title: 'Calculations are correct. Kirchhoff’s Voltage Law (KVL) has been verified successfully. Now, click on the Generate Report button.',
    type: 'success',
  },
  comparingValues: {
    description: 'The console is comparing measured branch currents with expected values.',
    duration: 2200,
    icon: '📊',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: 'Comparing Practical and Theoretical Values',
    type: 'info',
  },
  kclVerified: {
    description: 'The total current equals the sum of branch currents within tolerance.',
    icon: '✅',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: "Kirchhoff's Current Law Verified Successfully",
    type: 'success',
  },
  valuesDeviate: {
    description: 'Check wiring, resistance values, and recorded readings before continuing.',
    icon: '⚠️',
    stepNumber: 8,
    target: '#observation-table-panel',
    title: 'Observed Values Deviate from Expected Results',
    type: 'warning',
  },
  generatingGraph: {
    description: 'The graph panel is preparing current-versus-voltage traces.',
    duration: 1900,
    icon: '📊',
    stepNumber: 9,
    target: '#graph-panel',
    title: 'Generating Experimental Graph...',
    type: 'info',
  },
  graphPlotted: {
    audio: ALERT_AUDIO.graph,
    description: 'Your simulation is now complete. You may view the report by clicking on the generate report button, then use print to print the page or reset to start the simulation again.',
    icon: '✅',
    stepNumber: 9,
    target: '#generate-report-button',
    title: 'The graph of current vs voltage has been plotted successfully.',
    type: 'success',
  },
  insufficientGraphReadings: {
    audio: ALERT_AUDIO.insufficientReadings,
    description: 'Please add at least three readings before verifying KVL.',
    icon: '❌',
    stepNumber: 9,
    target: '#observation-table-panel',
    title: 'Insufficient Readings for Verification',
    type: 'error',
  },
  preparingReport: {
    description: 'The print view is being prepared from the current observations.',
    duration: 2000,
    icon: '📊',
    stepNumber: 10,
    target: '#print-button',
    title: 'Preparing Experiment Report for Printing',
    type: 'info',
  },
  printLayoutGenerated: {
    audio: ALERT_AUDIO.reportGenerated,
    description: 'Your report has been generated successfully. Click OK to view your report.',
    icon: '✅',
    stepNumber: 10,
    target: '#generate-report-button',
    title: 'Report Generated',
    type: 'success',
  },
  resettingSetup: {
    description: 'The lab system is returning controls to their initial state.',
    duration: 1800,
    icon: '🎛️',
    stepNumber: 11,
    target: '#reset-button',
    title: 'Resetting Experiment Setup...',
    type: 'info',
  },
  resetWarning: {
    confirmLabel: 'OK',
    dedupeKey: 'step-11-reset-warning',
    description: 'Confirm reset before the current table and circuit are cleared.',
    icon: '⚠️',
    placement: 'center',
    requiresConfirmation: true,
    stepNumber: 11,
    target: '#reset-button',
    title: 'All Readings and Connections Will Be Cleared',
    type: 'warning',
  },
  resetSuccess: {
    audio: ALERT_AUDIO.reset,
    description: '',
    icon: '✅',
    stepNumber: 11,
    target: '#circuit-panel',
    title: 'The simulation has been reset. You can start again.',
    type: 'success',
  },
}
